name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint yamllint
        
    - name: Run YAML Lint
      run: |
        yamllint .
        
    - name: Run Ansible Lint
      run: |
        ansible-lint playbooks/
        
    - name: Syntax Check
      run: |
        ansible-playbook --syntax-check playbooks/*.yml

  test:
    name: Test Playbooks
    runs-on: ubuntu-latest
    needs: lint
    
    strategy:
      matrix:
        ansible-version: [2.9, 4.0, 5.0]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Ansible ${{ matrix.ansible-version }}
      run: |
        python -m pip install --upgrade pip
        pip install ansible==${{ matrix.ansible-version }}
        
    - name: Test inventory parsing
      run: |
        ansible-inventory -i inventory --list
        
    - name: Dry run playbooks
      run: |
        for playbook in playbooks/*.yml; do
          echo "Testing $playbook"
          ansible-playbook -i inventory --check --diff "$playbook"
        done

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      uses: securecodewarrior/github-action-add-sarif@v1
      with:
        sarif-file: 'results.sarif'
      continue-on-error: true
